version: '0.0.1'
services:
  postgres:
    image: postgres:16.1
    container_name: english-course-app-postgres
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
